### ISSUE TITLE
Safe panics when trying to copy from a specific version

### ISSUE THREAD

**Issue by daviddob** [starkandwayne/safe#222]
When using a KV2 backend trying to copy from a specific version causes safe to panic.

```bash
./safe cp secret/test^3 secret/hmm
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/starkandwayne/safe/vault.(*Vault).Copy(0xc000061d00, 0x7ffeefbff4e2, 0xd, 0xc0002a3d50, 0xc, 0x0, 0x2, 0xc000155e58)
	/Users/dks0579496/go/src/github.com/starkandwayne/safe/vault/vault.go:663 +0xa2f
main.main.func32(0x13b57ec, 0x4, 0xc000384bc0, 0x2, 0x2, 0xc000372601, 0x0)
	/Users/dks0579496/go/src/github.com/starkandwayne/safe/main.go:2706 +0x2fc
main.(*Runner).Execute(0xc000060ff0, 0x13b57ec, 0x4, 0xc000384bc0, 0x2, 0x2, 0x0, 0x0)
	/Users/dks0579496/go/src/github.com/starkandwayne/safe/runner.go:117 +0x9b
main.main()
	/Users/dks0579496/go/src/github.com/starkandwayne/safe/main.go:4161 +0x2895
```

**Comment by daviddob** [comment]
Additional information - it appears that `safe cp` ignores the version and tries to copy the latest version. If that version happens to be deleted or destroyed then it causes the panic.
